### ISSUE TITLE
Issue on Wazuh 3.11.4

### ISSUE THREAD

**Issue by eyaladmin** [Hestat/ossec-sysmon#1]
Hi
it looks wonderful configuration to use, but I did not manage to use it on the latest Wazuh
it might be that they add some rule already "0330-sysmon_rules.xml" in the path:
/var/ossec/ruleset/rules/

The error looks like this:

Feb 29 19:48:27 manager systemd[1]: Starting Wazuh manager...
Feb 29 19:48:27 manager env[6611]: 2020/02/29 19:48:27 ossec-analysisd: ERROR: Duplicate rule ID:255571
Feb 29 19:48:27 manager env[6611]: 2020/02/29 19:48:27 ossec-analysisd: CRITICAL: (1220): **Error loading the rules: 'etc/rules/local_rules.xml'.**
Feb 29 19:48:27 manager env[6611]: ossec-analysisd: Configuration error. Exiting
Feb 29 19:48:27 manager systemd[1]: wazuh-manager.service: control process exited, code=exited status=1
Feb 29 19:48:27 manager systemd[1]: Failed to start Wazuh manager.
Feb 29 19:48:27 manager systemd[1]: Unit wazuh-manager.service entered failed state.
Feb 29 19:48:27 manager systemd[1]: wazuh-manager.service failed.

**Comment by Hestat** [comment]
Sorry about that I was testing adding a new rule and forgot to regenerate the configuration file after making a mistake in naming 2 rules with the same ID. This has been fixed. If you happen to run into it again in the future I'd recommend running the generate-config.sh script as I've usually fixed it but forgotten like this time to regen the config for upload!
