### ISSUE TITLE
Question about list for Malware

### ISSUE THREAD

**Issue by John33000** [Hestat/ossec-sysmon#2]
Hi, I use Wazuh 3.12.3. 

I would like use your rule : 

```
<group name="command and control">

<rule id="256000" level="0">
  <if_group>sysmon_event3</if_group>
  <list field="win.eventdata.destinationIp" lookup="address_match_key">etc/lists/emotet-list</list>
  <description>IP connection to Emotet Command and Control</description>
  <group>emotet,</group>
</rule>

```

But where is `/etc/list/emotet-list` ? What's inside?

**Comment by Hestat** [comment]
this was bit of an experimental feature, there's  no list created as a part of this project, but the contents were going to come from the cryptolaemus group's tracking of emotet C2, you can find the daily data dumps here: https://paste.cryptolaemus.com/
